using System;
using System.Collections.Generic;
using CardGame.Core.Players;

namespace CardGame.Core.Game
{
    /// <summary>
    /// Represents the complete runtime state of a card game.
    ///
    /// GameState stores data only.
    /// Game rules and game flow are handled by GameEngine/GameRules.
    /// </summary>
    public sealed class GameState
    {
        private readonly List<PlayerState> _players;
        private readonly List<GameEvent> _events;

        /// <summary>
        /// Unique identifier for this game instance.
        /// </summary>
        public string GameId { get; }

        /// <summary>
        /// Current phase of the game.
        /// </summary>
        public GamePhase Phase { get; internal set; }

        /// <summary>
        /// Indicates whether the game has finished.
        /// </summary>
        public bool IsGameOver { get; internal set; }

        /// <summary>
        /// Identifier of the player whose turn is currently active.
        /// </summary>
        public int CurrentPlayerId { get; internal set; }

        /// <summary>
        /// Number of the current turn.
        /// </summary>
        public int TurnNumber { get; internal set; }

        /// <summary>
        /// Identifier of the winner.
        /// Null means that the game has not finished yet.
        /// </summary>
        public int? WinnerId { get; internal set; }

        /// <summary>
        /// Players currently participating in the game.
        /// </summary>
        public IReadOnlyList<PlayerState> Players => _players;

        /// <summary>
        /// Events generated by the game engine.
        /// </summary>
        public IReadOnlyList<GameEvent> Events => _events;

        public GameState(
            string gameId,
            int startingPlayerId)
        {
            if (string.IsNullOrWhiteSpace(gameId))
                throw new ArgumentException(
                    "Game id cannot be empty.",
                    nameof(gameId));

            GameId = gameId;

            _players = new List<PlayerState>();
            _events = new List<GameEvent>();

            Phase = GamePhase.Setup;
            IsGameOver = false;
            CurrentPlayerId = startingPlayerId;
            TurnNumber = 0;
            WinnerId = null;
        }

        /// <summary>
        /// Adds a player to the current game.
        /// </summary>
        internal void AddPlayer(PlayerState player)
        {
            if (player == null)
                throw new ArgumentNullException(nameof(player));

            if (FindPlayer(player.Id) != null)
                throw new InvalidOperationException(
                    $"A player with id {player.Id} already exists.");

            _players.Add(player);
        }

        /// <summary>
        /// Finds a player by id.
        /// </summary>
        public PlayerState FindPlayer(int playerId)
        {
            for (int i = 0; i < _players.Count; i++)
            {
                if (_players[i].Id == playerId)
                    return _players[i];
            }

            return null;
        }

        /// <summary>
        /// Adds a game event to the event history.
        /// </summary>
        internal void AddEvent(GameEvent gameEvent)
        {
            _events.Add(gameEvent);
        }

        /// <summary>
        /// Clears the current state so the same GameState
        /// can be initialized for another match.
        /// </summary>
        internal void Reset()
        {
            _players.Clear();
            _events.Clear();

            Phase = GamePhase.Setup;
            IsGameOver = false;
            CurrentPlayerId = 0;
            TurnNumber = 0;
            WinnerId = null;
        }
    }
}
